//Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.
function evenFibo(x){
    var fib1 = 1; 
    var fib2 = 1; 
    var sum = 0; 
    while(fib2 < x){
      if(fib2 % 2 === 0){
        sum += fib2; 
      }
      var next = fib1 + fib2; 
      fib1 = fib2; 
      fib2 = next; 
    }
    return sum; 
  }
  console.log(evenFibo(4000000))
  //Answer: 4613732